### ISSUE TITLE
Selects Current Field as Text on Firefox

### ISSUE THREAD

**Issue by maracuja-juice** [maracuja-juice/ultimate-tic-tac-react#1]
Repro Steps:
1. Click on Field

Expected Result: 
- Sets an icon & marks the new small board

Actual Result: 
- Sets an icon & marks the new small board
- Shows a popup with "Copy" etc.

Screenshot:
![screenshot_20180223-212132_01](https://user-images.githubusercontent.com/16801528/36615926-4a81031a-18e2-11e8-86bb-ce59191081cf.png)

**Comment by maracuja-juice** [comment]
(this only happens in Firefox)

In Edge/Brave/Opera (all on Android) this is not a problem.

**Comment by maracuja-juice** [comment]
The same behaviour can be seen on desktop Firefox.

**Comment by RohrerF** [comment]
@maracuja-juice maybe [this](https://stackoverflow.com/a/6900392/6271609) helps

**Comment by maracuja-juice** [comment]
@RohrerF Thanks. this does indeed work. Pull Request: #39
