### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by RohrerF** [maracuja-juice/ultimate-tic-tac-react#14]
Use a cooler logo than the default

**Comment by maracuja-juice** [comment]
Not sure what we can use here. Here's a first idea:

![screen shot 2018-03-01 at 19 55 52](https://user-images.githubusercontent.com/16801528/36863648-9e2b7552-1d8a-11e8-8c4a-c08f1a4a9314.jpg)

**Comment by maracuja-juice** [comment]
X/O as a logo would be a different idea.

**Comment by maracuja-juice** [comment]
![android-chrome-192x192](https://user-images.githubusercontent.com/16801528/38057541-187b02d6-32e0-11e8-97d7-dd242834acd8.png)
